
tasks:
  - name: Install AWS CLI and Configure
    init: |
      # Install AWS CLI
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      
      # Configure AWS credentials
      aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
      aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
      aws configure set default.region ${AWS_REGION}
      aws configure set output json

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode